# This is a basic workflow to help you get started with Actions

name: Github Action Maven Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout the main branch from Github
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 - Setup JDK 1.7
        uses: actions/setup-java@v1
        with:
           java-version: 1.7
           
       # Runs a set of commands using the runners shell
#       - name: Step 3 - Github Actions Building Maven Project
#         run:  cd cleansweep
        
      # Runs a set of commands using the runners shell
      - name: Step 3 - Github Actions Building Maven Project
        run: | 
           # mvn -B package --file /home/runner/work/GithubActionsTest/GithubActionsTest/cleansweep/pom.xml
           # mvn clean install --projects :--file /home/runner/work/GithubActionsTest/GithubActionsTest/cleansweep/pom.xml,:then- --file /home/runner/work/GithubActionsTest/GithubActionsTest/sensor-simulator/pom.xml
           # mvn -pl cleansweep -B package --file /home/runner/work/GithubActionsTest/GithubActionsTest/sensor-simulator/pom.xml
           # mvn clean install -pl "/home/runner/work/GithubActionsTest/GithubActionsTest/cleansweep/pom.xml"/"/home/runner/work/GithubActionsTest/GithubActionsTest/sensor-simulator/pom.xml"
           mvn -B package --file /home/runner/work/GithubActionsTest/GithubActionsTest/control-system/pom.xml

      # Runs a set of commands using the runners shell
#       - name: Step 4 - Github Actions Building Maven Project
#         run:  mvn -B package --file /home/runner/work/GithubActionsTest/GithubActionsTest/sensor-simulator/pom.xml
        
      # Runs a set of commands using the runners shell
#       - name: Step 5 - Github Actions Building Maven Project
#         run:  mvn -B package --file /home/runner/work/GithubActionsTest/GithubActionsTest/control-system/pom.xml
        
      - name: Step 6 - Get the tareget folder path
        run: | 
         ls -a /home/runner/work/GithubActionsTest/GithubActionsTest/cleansweep/target
